Update Pervasives.compare to Stdlib.compare
Pervasives has been renamed sometime before OCaml 5.2.0,
the most recent version that I have in a switch.

Here's the error without this patch applied.

```
sh:2 $ make
ocamlbuild -no-links -use-ocamlfind -I termlib src/main.native
+ ocamlfind ocamlc -c -g -annot -w -23 -w -40 -package unix -I termlib -o termlib/key.cmo termlib/key.ml
File "termlib/key.ml", line 1538, characters 17-35:
1538 |   let compare = (Pervasives.compare: t -> t -> int)
                        ^^^^^^^^^^^^^^^^^^
Error: Unbound module "Pervasives"
Command exited with code 2.
Compilation unsuccessful after building 21 targets (18 cached) in 00:00:00.
make: *** [Makefile:12: red] Error 10
  2
```

Here's the warning you get with OCaml 4.13.1, which explains how to fix the problem.

```
+ ocamlfind ocamlc -c -g -annot -w -23 -w -40 -package unix -I src -I termlib -o src/file.cmo src/file.ml
File "src/file.ml", line 126, characters 16-34:
126 |   let compare = Pervasives.compare
                      ^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.
```